#!/bin/bash

function _ssh_env() {
  export SSH_CURRENT="${1}"
  key=""
  if [[ $# -ge 1 ]] && key="${1}"
    then
      export GIT_SSH_COMMAND="ssh -i $key"
  fi
  if [[ $# -le 0 ]] && command -v fzf
    then
      keys="$(_ssh_list_keys | fzf --prompt "keys: " -m)"
      export GIT_SSH_COMMAND="ssh -i $keys"
      unset SSH_CURRENT
      export SSH_CURRENT="${keys}"
  fi
}

function _ssh_unset() {
  unset GIT_SSH_COMMAND
  unset SSH_DEFAULT
  unset SSH_CURRENT
}

function _ssh_list_keys() {

  while read line; do
      echo "$line";
  done < <(ls -1 ~/.ssh/* | sed -e 's/\.pub$//' | sort | uniq | grep -v known_hosts);
};

alias ssh-switch="_ssh_env"
alias ssh-unset="_ssh_unset"
alias ssh-list="_ssh_list_keys"
alias ssh-which='echo $SSH_CURRENT'

ssh-switch ${SSH_DEFAULT}
